language: generic
matrix:
    include:
        - language: rust
          rust: stable
        - language: rust
          rust: beta
        - language: rust
          rust: nightly

script:
    - if [ -n "$TRAVIS_RUST_VERSION" ]; then
          cd server;
          cargo test;
      fi

